"""Settlewell — Ground settlement calculation for dewatering of construction pits.

Berekening van grondverzakking door bronbemaling bij bouwputten.
"""

from .damage import (
    SBR_THRESHOLDS,
    DamageAssessment,
    assess_building_damage,
    classify_damage,
)
from .hydraulics import (
    compute_drawdown_at_points,
    compute_drawdown_grid,
    compute_radius_of_influence,
    compute_storativity,
    compute_transmissivity,
    theis_drawdown_single_well,
    thiem_drawdown_single_well,
)
from .models import (
    AquiferType,
    Building,
    BuildingType,
    ConstructionPit,
    DesignApproach,
    DewateringConfig,
    DrainageType,
    FlemishSoilType,
    LoadGeometry,
    LoadType,
    SoilLayer,
    SoilProfile,
    SoilTypeUSCS,
    SolverSettings,
    StressMethod,
    Well,
)
from .numerical import (
    FDGrid,
    create_grid,
    extract_drawdown_at_points,
    solve_steady_state,
)
from .plotting import (
    plot_3d_drawdown,
    plot_3d_drawdown_mpl,
    plot_cross_section,
    plot_damage_summary,
    plot_effective_stress_profile,
    plot_plan_view,
    plot_settlement_trough,
    plot_time_settlement,
)
from .settlement import (
    compute_degree_of_consolidation,
    compute_initial_stress_profile,
    compute_layer_settlement_cc_cr,
    compute_layer_settlement_eoed,
    compute_settlement_vs_time,
    compute_stress_increase_from_drawdown,
    compute_total_settlement,
)
from .stress import (
    boussinesq_rectangular_stress,
    boussinesq_strip_stress,
    compute_load_stress_increment,
    compute_stress_heatmap,
    compute_stress_profile_under_loads,
    fadum_corner_stress,
)

__version__ = "0.1.0"

__all__ = [
    "SBR_THRESHOLDS",
    "AquiferType",
    "Building",
    "BuildingType",
    "ConstructionPit",
    "DamageAssessment",
    "DesignApproach",
    "DewateringConfig",
    "DrainageType",
    "FDGrid",
    "FlemishSoilType",
    "LoadGeometry",
    "LoadType",
    "SoilLayer",
    "SoilProfile",
    "SoilTypeUSCS",
    "SolverSettings",
    "StressMethod",
    "Well",
    "__version__",
    "assess_building_damage",
    "boussinesq_rectangular_stress",
    "boussinesq_strip_stress",
    "classify_damage",
    "compute_degree_of_consolidation",
    "compute_drawdown_at_points",
    "compute_drawdown_grid",
    "compute_initial_stress_profile",
    "compute_layer_settlement_cc_cr",
    "compute_layer_settlement_eoed",
    "compute_load_stress_increment",
    "compute_radius_of_influence",
    "compute_settlement_vs_time",
    "compute_storativity",
    "compute_stress_heatmap",
    "compute_stress_increase_from_drawdown",
    "compute_stress_profile_under_loads",
    "compute_total_settlement",
    "compute_transmissivity",
    "create_grid",
    "extract_drawdown_at_points",
    "fadum_corner_stress",
    "plot_3d_drawdown",
    "plot_3d_drawdown_mpl",
    "plot_cross_section",
    "plot_damage_summary",
    "plot_effective_stress_profile",
    "plot_plan_view",
    "plot_settlement_trough",
    "plot_time_settlement",
    "solve_steady_state",
    "theis_drawdown_single_well",
    "thiem_drawdown_single_well",
]
